"""create providers table

Revision ID: 3c59b969e6ea
Revises: 
Create Date: 2026-09-20 11:58:55.728189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c59b969e6ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_states', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('specialties', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('modalities', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('insurance_panels', postgresql.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('weekly_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providers')
    # ### end Alembic commands ###
