"""create clients table

Revision ID: 5c959c18a6ed
Revises: 3c59b969e6ea
Create Date: 2026-09-21 13:27:25.261633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c959c18a6ed'
down_revision: Union[str, Sequence[str], None] = '3c59b969e6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('insurance_payer', sa.String(length=255), nullable=False),
    sa.Column('needed_specialties', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('preferred_modality', sa.String(length=32), nullable=False),
    sa.Column('preferred_language', sa.String(length=64), nullable=False),
    sa.Column('urgency', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
