"""create simulation_runs table and link clients and providers

Revision ID: 6fced15d4656
Revises: 68d618a41517
Create Date: 2026-09-23 16:19:18.144114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fced15d4656'
down_revision: Union[str, Sequence[str], None] = '68d618a41517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('provider_count', sa.Integer(), nullable=False),
    sa.Column('client_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('simulation_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key('clients_simulation_run_id_fkey', 'clients', 'simulation_runs', ['simulation_run_id'], ['id'])
    op.add_column('providers', sa.Column('simulation_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key('providers_simulation_run_id_fkey', 'providers', 'simulation_runs', ['simulation_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('providers_simulation_run_id_fkey', 'providers', type_='foreignkey')
    op.drop_column('providers', 'simulation_run_id')
    op.drop_constraint('clients_simulation_run_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'simulation_run_id')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
