"""add scenario to simulation_runs and arrival_day to clients

Revision ID: 9e683e6c7f9c
Revises: 6fced15d4656
Create Date: 2026-09-23 16:34:42.513798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e683e6c7f9c'
down_revision: Union[str, Sequence[str], None] = '6fced15d4656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('arrival_day', sa.Integer(), nullable=True))
    op.add_column('simulation_runs', sa.Column('scenario', sa.String(length=64), server_default='balanced', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'scenario')
    op.drop_column('clients', 'arrival_day')
    # ### end Alembic commands ###
